language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
     - PLATFORMIO_CI_SRC=src/main.cpp

install:
    - pip install -U platformio
    - platformio lib -g install 64 89 560 567

script:
    - platformio ci --project-conf=platformio.ini
